In [1]:
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')
%matplotlib inline

In [2]:
df = pd.read_csv("salary/h1b_salary_clean.txt",header = None,sep = "," ,low_memory=False)

In [7]:
df[3].value_counts()

CERTIFIED    245465
WITHDRAWN      9778
DENIED         2661
Name: 3, dtype: int64

In [9]:
df2 = pd.read_csv("salary_skill_joined/part-00000",header = None,sep = "," ,low_memory=False)

In [10]:
df2

,0,1,2,3,4,5,6,7,8
0,((crescent,software engineer),((100000,CERTIFIED,CA,2015,3),(48,0)))
1,((foundation,software engineer),((70000,CERTIFIED,OH,2017,3),(400,0)))
2,((ubs,software engineer),((70500,CERTIFIED,NY,2017,3),(24,3)))
3,((ubs,software engineer),((69500,WITHDRAWN,NJ,2012,3),(24,3)))
4,((ubs,software engineer),((69500,WITHDRAWN,NJ,2012,3),(24,3)))
5,((ubs,software engineer),((69500,WITHDRAWN,NJ,2012,3),(24,3)))
6,((ubs,software engineer),((70970,WITHDRAWN,NJ,2012,12),(24,3)))
7,((ubs,software engineer),((70970,WITHDRAWN,NJ,2013,1),(24,3)))
8,((ubs,software engineer),((110000,CERTIFIED,NJ,2014,12),(24,3)))
9,((ubs,software engineer),((75000,WITHDRAWN,NJ,2014,4),(24,3)))
10,((ubs,software engineer),((81000,WITHDRAWN,NJ,2014,5),(24,3)))
11,((ubs,software engineer),((81000,WITHDRAWN,NJ,2015,3),(24,3)))
12,((ubs,software engineer),((81000,CERTIFIED,NJ,2015,3),(24,3)))
13,((ubs,software engineer),((73445,WITHDRAWN,NJ,2015,3),(24,3)))
14,((ubs,software engineer),((73445,WITHDRAWN,CT,2015,4),(24,3)))
15,((ubs,software engineer),((73445,CERTIFIED,NJ,2015,3),(24,3)))
16,((ubs,software engineer),((73445,CERTIFIED,CT,2015,4),(24,3)))
17,((ubs,software engineer),((73445,CERTIFIED,NJ,2015,4),(24,3)))
18,((ubs,software engineer),((56867,WITHDRAWN,CT,2016,3),(24,3)))
19,((ubs,software engineer),((59700,CERTIFIED,TN,2016,2),(24,3)))
20,((ubs,software engineer),((62000,CERTIFIED,NJ,2016,2),(24,3)))
21,((cis,software engineer),((159099,CERTIFIED,CA,2017,3),(263,0)))
22,((cis,software engineer),((80205,CERTIFIED,GA,2017,2),(263,0)))
23,((cis,software engineer),((82098,CERTIFIED,TX,2017,3),(263,0)))
24,((cis,software engineer),((82098,CERTIFIED,TX,2017,3),(263,0)))
25,((cis,software engineer),((82640,CERTIFIED,TX,2017,12),(263,0)))
26,((cis,software engineer),((83570,CERTIFIED,NC,2017,12),(263,0)))
27,((cis,software engineer),((84180,CERTIFIED,MD,2017,12),(263,0)))
28,((cis,software engineer),((91624,CERTIFIED,CO,2017,2),(263,0)))
29,((cis,software engineer),((92074,CERTIFIED,MA,2017,12),(263,0)))
...,...,...,...,...,...,...,...,...,...
422,((docusign,software engineer),((140000,CERTIFIED,CA,2018,8),(384,6)))
423,((docusign,software engineer),((95000,CERTIFIED,IL,2019,2),(384,6)))
424,((docusign,software engineer),((105000,CERTIFIED,IL,2019,4),(384,6)))
425,((docusign,software engineer),((130000,CERTIFIED,WA,2019,1),(384,6)))
426,((docusign,software engineer),((135000,CERTIFIED,WA,2019,6),(384,6)))
427,((docusign,software engineer),((141700,CERTIFIED,CA,2019,8),(384,6)))
428,((docusign,software engineer),((81500,CERTIFIED,WA,2014,10),(384,6)))
429,((docusign,software engineer),((105000,CERTIFIED,CA,2015,9),(384,6)))
430,((docusign,software engineer),((115000,CERTIFIED,CA,2015,7),(384,6)))
431,((docusign,software engineer),((130486,CERTIFIED,CA,2015,11),(384,6)))
432,((docusign,software engineer),((130000,CERTIFIED,CA,2016,7),(384,6)))
433,((docusign,software engineer),((96866,CERTIFIED,CA,2016,6),(384,6)))
434,((docusign,software engineer),((113381,CERTIFIED,CA,2016,12),(384,6)))
435,((docusign,software engineer),((115000,CERTIFIED,WA,2016,2),(384,6)))
436,((docusign,software engineer),((122533,CERTIFIED,WA,2016,10),(384,6)))
437,((docusign,software engineer),((105102,CERTIFIED,IL,2016,2),(384,6)))
438,((docusign,software engineer),((105500,WITHDRAWN,IL,2016,2),(384,6)))
439,((docusign,software engineer),((106101,CERTIFIED,WA,2016,8),(384,6)))
440,((docusign,software engineer),((125000,CERTIFIED,CA,2016,3),(384,6)))
441,((docusign,software engineer),((141000,CERTIFIED,CA,2016,2),(384,6)))
442,((extrahop,software engineer),((95000,CERTIFIED,WA,2017,3),(85,0)))
443,((pilack,software engineer),((115000,CERTIFIED,MA,2017,3),(12,1)))
444,((pilack,software engineer),((150500,CERTIFIED,MA,2018,11),(12,1)))
445,((pilack,software engineer),((113600,CERTIFIED,MA,2019,1),(12,1)))
446,((pilack,software engineer),((110500,CERTIFIED,MA,2019,5),(12,1)))
447,((pilack,software engineer),((137100,CERTIFIED,WA,2019,3),(12,1)))
448,((pilack,software engineer),((137100,CERTIFIED,WA,2019,3),(12,1)))
449,((pilack,software engineer),((75000,CERTIFIED,MA,2016,11),(12,1)))
450,((pilack,software engineer),((115000,CERTIFIED,MA,2016,7),(12,1)))
451,((eagleview,software engineer),((117000,CERTIFIED,WA,2017,9),(16,0)))